/**
 * Java 方法信息接口
 */
interface MethodInfo {
  name: string;
  returnType: string;
  parameters: string[];
  description?: string;
  modifiers: string;
  isStatic: boolean;
  isPublic: boolean;
  exceptions?: string[];
}

/**
 * Java 反射数据接口
 */
interface ReflectionData {
  className: string;
  superClass?: string | null;
  interfaces?: string[];
  methods: MethodInfo[];
}

/**
 * Java 到 TypeScript 类型映射表
 */
const JAVA_TO_TS_TYPE_MAP: Record<string, string> = {
  // Java 基础类型
  'java.lang.String': 'string',
  'java.lang.Integer': 'number',
  'java.lang.Long': 'number',
  'java.lang.Double': 'number',
  'java.lang.Float': 'number',
  'java.lang.Boolean': 'boolean',
  'java.lang.Object': 'any',
  'java.lang.Class': 'any',
  
  // Java 原始类型
  'void': 'void',
  'int': 'number',
  'long': 'number',
  'double': 'number',
  'float': 'number',
  'boolean': 'boolean',
  'byte': 'number',
  'short': 'number',
  'char': 'string',
  
  // Java 常用类
  'java.util.Date': 'Date',
  'java.util.List': 'Array<any>',
  'java.util.Map': 'Record<string, any>',
  'java.util.Set': 'Set<any>',
};

/**
 * .d.ts 文件生成器
 * 将 Maximo 反射 JSON 数据转换为 TypeScript 声明文件
 */
export class DtsGenerator {
  
  /**
   * 简化 Java 类型为 TypeScript 类型
   * @param javaType Java 类型（如：java.lang.String）
   * @returns TypeScript 类型（如：string）
   */
  simplifyJavaType(javaType: string): string {
    // 先查映射表
    if (JAVA_TO_TS_TYPE_MAP[javaType]) {
      return JAVA_TO_TS_TYPE_MAP[javaType];
    }
    
    // 如果是数组类型
    if (javaType.endsWith('[]')) {
      const elementType = javaType.slice(0, -2);
      const tsElementType = this.simplifyJavaType(elementType);
      return `${tsElementType}[]`;
    }
    
    // 如果是泛型类型（简单处理）
    if (javaType.includes('<') && javaType.includes('>')) {
      // 暂时返回 any，后续可以增强
      return 'any';
    }
    
    // 默认保持原样（Maximo 自定义类）
    return javaType;
  }
  
  /**
   * 生成方法签名
   * @param method 方法信息
   * @returns 方法签名字符串
   */
  generateMethodSignature(method: MethodInfo): string {
    const params = method.parameters.map(p => this.simplifyJavaType(p)).join(', ');
    const returnType = this.simplifyJavaType(method.returnType);
    return `${returnType} ${method.name}(${params})`;
  }
  
  /**
   * 生成 JSDoc 注释
   * @param method 方法信息
   * @returns JSDoc 注释字符串
   */
  generateJsDoc(method: MethodInfo): string {
    let jsdoc = '        /**\n';
    
    if (method.description) {
      jsdoc += `         * ${method.description}\n`;
    } else {
      jsdoc += `         * ${method.name} method\n`;
    }
    
    // 添加参数说明
    if (method.parameters.length > 0) {
      method.parameters.forEach((param, index) => {
        const paramName = `param${index + 1}`;
        const paramType = this.simplifyJavaType(param);
        jsdoc += `         * @param ${paramName} ${paramType}\n`;
      });
    }
    
    // 添加返回值说明
    if (method.returnType !== 'void') {
      const returnType = this.simplifyJavaType(method.returnType);
      jsdoc += `         * @returns ${returnType}\n`;
    }
    
    jsdoc += '         */\n';
    
    return jsdoc;
  }
  
  /**
   * 生成方法声明
   * @param method 方法信息
   * @returns 方法声明字符串
   */
  generateMethodDeclaration(method: MethodInfo): string {
    let declaration = '';
    
    // 添加静态修饰符
    if (method.isStatic) {
      declaration += '        static ';
    }
    
    // 添加 JSDoc
    declaration += this.generateJsDoc(method);
    
    // 生成方法签名
    const params = method.parameters.map((p, i) => {
      const paramName = `param${i + 1}`;
      const paramType = this.simplifyJavaType(p);
      return `${paramName}: ${paramType}`;
    }).join(', ');
    
    const returnType = this.simplifyJavaType(method.returnType);
    declaration += `        ${method.name}(${params}): ${returnType};\n`;
    
    return declaration;
  }
  
  /**
   * 解析类名，提取包名和简单类名
   * @param className 完整类名（如：com.ibm.tivoli.maximo.script.ScriptService）
   * @returns { packageName, simpleClassName }
   */
  parseClassName(className: string): { packageName: string; simpleClassName: string } {
    const lastDotIndex = className.lastIndexOf('.');
    
    if (lastDotIndex === -1) {
      return {
        packageName: '',
        simpleClassName: className
      };
    }
    
    return {
      packageName: className.substring(0, lastDotIndex),
      simpleClassName: className.substring(lastDotIndex + 1)
    };
  }
  
  /**
   * 生成完整的 .d.ts 文件内容
   * @param reflectionData 反射数据
   * @returns .d.ts 文件内容字符串
   */
  generateDtsContent(reflectionData: ReflectionData): string {
    const { className, superClass, interfaces, methods } = reflectionData;
    const { packageName, simpleClassName } = this.parseClassName(className);
    
    let content = '// Auto-generated by Maximo Script Helper\n';
    content += `// Source: ${className}\n`;
    content += `// Generated at: ${new Date().toISOString()}\n\n`;
    
    // 如果有包名，生成命名空间
    if (packageName) {
      content += `declare namespace ${packageName} {\n`;
    }
    
    // 类声明开始
    const indent = packageName ? '    ' : '';
    content += `${indent}/**\n`;
    content += `${indent} * ${simpleClassName} class\n`;
    
    if (superClass) {
      content += `${indent} * @extends ${this.simplifyJavaType(superClass)}\n`;
    }
    
    if (interfaces && interfaces.length > 0) {
      content += `${indent} * @implements ${interfaces.map(i => this.simplifyJavaType(i)).join(', ')}\n`;
    }
    
    content += `${indent} */\n`;
    content += `${indent}class ${simpleClassName}`;
    
    // 继承关系
    if (superClass) {
      content += ` extends ${this.simplifyJavaType(superClass)}`;
    }
    
    content += ` {\n`;
    
    // 生成所有公共方法
    const publicMethods = methods.filter(m => m.isPublic);
    
    for (const method of publicMethods) {
      content += this.generateMethodDeclaration(method);
      content += '\n';
    }
    
    content += `${indent}}\n`;
    
    // 闭合命名空间
    if (packageName) {
      content += `}\n`;
    }
    
    return content;
  }
  
  /**
   * 根据类名计算文件路径（相对于 javaapi 目录）
   * @param className 完整类名
   * @returns 文件路径（如：com/ibm/tivoli/maximo/script/ScriptService.d.ts）
   */
  calculateFilePath(className: string): string {
    const { packageName, simpleClassName } = this.parseClassName(className);
    
    if (!packageName) {
      return `${simpleClassName}.d.ts`;
    }
    
    // 将包名中的点号替换为斜杠
    const packagePath = packageName.replace(/\./g, '/');
    return `${packagePath}/${simpleClassName}.d.ts`;
  }
  
  /**
   * 根据类名计算 JSON 文件路径（相对于 reflection-data 目录）
   * @param className 完整类名
   * @returns 文件路径（如：com/ibm/tivoli/maximo/script/ScriptService.json）
   */
  calculateJsonFilePath(className: string): string {
    const { packageName, simpleClassName } = this.parseClassName(className);
    
    if (!packageName) {
      return `${simpleClassName}.json`;
    }
    
    // 将包名中的点号替换为斜杠
    const packagePath = packageName.replace(/\./g, '/');
    return `${packagePath}/${simpleClassName}.json`;
  }
}
