// Auto-generated by Maximo Script Helper
// Source: psdi.mbo.MboConstants
// Generated at: 2026-06-05T21:27:46.131Z

declare namespace psdi.mbo {
    /**
     * MboConstants class
     */
    class MboConstants {
        // No public methods available
        /** 1 */
        static readonly NOADD: bigint;
        /** 2 */
        static readonly NOUPDATE: bigint;
        /** 4 */
        static readonly NODELETE: bigint;
        /** 8 */
        static readonly NOSAVE: bigint;
        /** 16 */
        static readonly NO_RELATEDMBOS_OF_OWNERSCHILDREN_FETCH: bigint;
        /** 7 */
        static readonly READONLY: bigint;
        /** 32 */
        static readonly DISCARDABLE: bigint;
        /** 64 */
        static readonly NOSETVALUE: bigint;
        /** 128 */
        static readonly REQUIRED: bigint;
        /** 263 */
        static readonly HIDDEN: bigint;
        /** 512 */
        static readonly SAMEVALUEVALIDATION: bigint;
        /** 1024 */
        static readonly DBCONFIG: bigint;
        /** 2048 */
        static readonly GOTCOMPLETEWHERE: bigint;
        /** 524288 */
        static readonly SETBYPARENT: bigint;
        /** 1048576 */
        static readonly USER: bigint;
        /** 1 */
        static readonly NOVALIDATION: bigint;
        /** 2 */
        static readonly NOACCESSCHECK: bigint;
        /** 4 */
        static readonly DELAYVALIDATIONONLY: bigint;
        /** 8 */
        static readonly NOACTION: bigint;
        /** 9 */
        static readonly NOVALIDATION_AND_NOACTION: bigint;
        /** 16 */
        static readonly CHANGEDBY_USER: bigint;
        /** 32 */
        static readonly NOOVERWRITE: bigint;
        /** 36 */
        static readonly DELAYVALIDATION: bigint;
        /** 64 */
        static readonly NOVALIDATION_AND_NOACTION_ALLOWCROSSOVER: bigint;
        /** 0 */
        static readonly NONE: bigint;
        /** 10000000 */
        static readonly ALLROWS: number;
        /** 1 */
        static readonly REBUILD: bigint;
        /** 2 */
        static readonly NOCOMMIT: bigint;
        /** 1 */
        static readonly COUNT_DATABASE: number;
        /** 2 */
        static readonly COUNT_ADDITIONS: number;
        /** 4 */
        static readonly COUNT_DELETED: number;
        /** 8 */
        static readonly COUNT_EXISTING: number;
        /** 16 */
        static readonly COUNT_AFTERSAVE: number;
        /** 9223372036854775807 */
        static readonly BIGINT_UPPER: bigint;
        /** -9223372036854775808 */
        static readonly BIGINT_LOWER: bigint;
        /** 2147483647 */
        static readonly INTEGER_UPPER: number;
        /** -2147483648 */
        static readonly INTEGER_LOWER: number;
        /** 32767 */
        static readonly SMALLINT_UPPER: number;
        /** -32768 */
        static readonly SMALLINT_LOWER: number;
        /** "extqbectx" */
        static readonly EXT_QBE_CTX: string;
        /** "nonextqbectx" */
        static readonly NONEXT_QBE_CTX: string;

    }
}
